// Interface automatically generated by schemas-to-ts

import { Service } from '../../../service/content-types/service/service';
import { Service_Plain } from '../../../service/content-types/service/service';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Feedback {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    phoneNumber?: string;
    service?: { data: Service };
  };
}
export interface Feedback_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  phoneNumber?: string;
  service?: Service_Plain;
}

export interface Feedback_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  phoneNumber?: string;
  service?: number;
}

export interface Feedback_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  phoneNumber?: string;
  service?: AdminPanelRelationPropertyModification<Service_Plain>;
}
